### ISSUE TITLE
Can't compile on Linux

### ISSUE THREAD

**Issue by Csokis** [devinacker/bsnes-plus#246]
I can't compile on Xubuntu Linux 18.04 LTS. :(

> g++ -std=gnu++0x -fPIC -O3 -fomit-frame-pointer -I. -I../common -Icommon -Ilibgambatte/include -Ilibgambatte/src -c libgambatte/src/mem/cartridge.cpp -o obj/cartridge.o
libgambatte/src/mem/cartridge.cpp: In member function ‘void gambatte::Cartridge::loadSavedata()’:
libgambatte/src/mem/cartridge.cpp:672:125: error: no matching function for call to ‘min(long long int, long int)’
 ta, std::min((long long)supergameboy.ramsize, memptrs_.rambankdataend() - memptrs_.rambankdata()));
                                                                                                 ^
In file included from /usr/include/c++/7/bits/char_traits.h:39:0,
                 from /usr/include/c++/7/string:40,
                 from libgambatte/include/loadres.h:4,
                 from libgambatte/src/mem/cartridge.h:22,
                 from libgambatte/src/mem/cartridge.cpp:19:
/usr/include/c++/7/bits/stl_algobase.h:195:5: note: candidate: template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)
     min(const _Tp& __a, const _Tp& __b)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:195:5: note:   template argument deduction/substitution failed:
libgambatte/src/mem/cartridge.cpp:672:125: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long long int’ and ‘long int’)
 ta, std::min((long long)supergameboy.ramsize, memptrs_.rambankdataend() - memptrs_.rambankdata()));
                                                                                                 ^
In file included from /usr/include/c++/7/bits/char_traits.h:39:0,
                 from /usr/include/c++/7/string:40,
                 from libgambatte/include/loadres.h:4,
                 from libgambatte/src/mem/cartridge.h:22,
                 from libgambatte/src/mem/cartridge.cpp:19:
/usr/include/c++/7/bits/stl_algobase.h:243:5: note: candidate: template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:243:5: note:   template argument deduction/substitution failed:
libgambatte/src/mem/cartridge.cpp:672:125: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long long int’ and ‘long int’)
 ta, std::min((long long)supergameboy.ramsize, memptrs_.rambankdataend() - memptrs_.rambankdata()));
                                                                                                 ^
libgambatte/src/mem/cartridge.cpp: In member function ‘void gambatte::Cartridge::saveSavedata()’:
libgambatte/src/mem/cartridge.cpp:692:103: error: no matching function for call to ‘min(long long int, long int)’
     std::min((long long)supergameboy.ramsize, memptrs_.rambankdataend() - memptrs_.rambankdata()));
                                                                                                 ^
In file included from /usr/include/c++/7/bits/char_traits.h:39:0,
                 from /usr/include/c++/7/string:40,
                 from libgambatte/include/loadres.h:4,
                 from libgambatte/src/mem/cartridge.h:22,
                 from libgambatte/src/mem/cartridge.cpp:19:
/usr/include/c++/7/bits/stl_algobase.h:195:5: note: candidate: template<class _Tp> const _Tp& std::min(const _Tp&, const _Tp&)
     min(const _Tp& __a, const _Tp& __b)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:195:5: note:   template argument deduction/substitution failed:
libgambatte/src/mem/cartridge.cpp:692:103: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long long int’ and ‘long int’)
     std::min((long long)supergameboy.ramsize, memptrs_.rambankdataend() - memptrs_.rambankdata()));
                                                                                                 ^
In file included from /usr/include/c++/7/bits/char_traits.h:39:0,
                 from /usr/include/c++/7/string:40,
                 from libgambatte/include/loadres.h:4,
                 from libgambatte/src/mem/cartridge.h:22,
                 from libgambatte/src/mem/cartridge.cpp:19:
/usr/include/c++/7/bits/stl_algobase.h:243:5: note: candidate: template<class _Tp, class _Compare> const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/usr/include/c++/7/bits/stl_algobase.h:243:5: note:   template argument deduction/substitution failed:
libgambatte/src/mem/cartridge.cpp:692:103: note:   deduced conflicting types for parameter ‘const _Tp’ (‘long long int’ and ‘long int’)
     std::min((long long)supergameboy.ramsize, memptrs_.rambankdataend() - memptrs_.rambankdata()));
                                                                                                 ^
Makefile:36: recipe for target 'obj/cartridge.o' failed
make[1]: *** [obj/cartridge.o] Error 1
make[1]: Leaving directory '/mnt/minden/Sources/bsnes-plus/supergameboy'
Makefile:130: recipe for target 'plugins' failed
make: *** [plugins] Error 2

**Comment by devinacker** [comment]
Try applying fc5f8514396b2f34d8f941a4ee82db1f42e54de8 and see if that fixes it.

**Comment by Csokis** [comment]
Perfect! :+1: Thank You! :)
